name: Docker Image for GHCR

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build . -t ghcr.io/chrischizinski/tidyr:latest
      - name: Push Docker Image
        run: docker push ghcr.io/chrischizinski/tidyr:latest
