name: ci
#
on:
  push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - 
      name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: chrischizinski
          password: ${{secrets.GITHUB_TOKEN}}
      
      - 
      name: 'Build and push image'
            run: |
              docker build . --tag ghcr.io/chrischizinski/tidyr:latest
              docker push ghcr.io/chrischizinski/tidyr:latest